name: Sync to Gitea

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Push to Gitea
        run: |
          git config --global user.name "Push From Github"
          git config --global user.email "actions@github.com"
          git remote add gitea http://$GITEA_USER:$GITEA_TOKEN@git.community-scripts.org/community-scripts/ProxmoxVED.git
          git push gitea --mirror
        env:
          GITEA_USER: ${{ secrets.GITEA_USERNAME }}
          GITEA_TOKEN: ${{ secrets.GITEA_TOKEN }}
